import type { Metadata } from 'next';
import './styles/globals.css';
import Header from '@/app/components/common/Header';
import localFont from 'next/font/local';

const pretendardM = localFont({
  src: './fonts/Pretendard-Medium.otf',
  weight: 'normal',
  style: 'normal'
});

const pretendardR = localFont({
  src: './fonts/Pretendard-Regular.otf',
  weight: 'normal',
  style: 'normal'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Header />
      <body className={`${pretendardM.className} ${pretendardR.className}`}>{children}</body>
    </html>
  );
}
